categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
autolabeler:
  - label: 'feature'
    title: 
      - '/^Feature\/.+/'
  - label: 'bug'
      - '/fix\/.+/'
    title:
      - '/Fix/i'
template: |
  ## What’s Changed

  $CHANGES
