on:
  release:
    types:
      - released

name: Jira Release

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Release
    steps:
    - name: Create Jira version
      run: |
        curl --user ${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} \
             --header "Content-Type: application/json" \
             --url 'https://actionstest.atlassian.net/rest/api/3/version' \
             -X POST \
             --data '{ "name": "'"${{ github.event.release.name }}"'", "released": true, "releaseDate": "'"$(date +'%Y-%m-%d')"'", "projectId": 10000, "description": "'"${{ github.event.release.html_url }}"'" }'
