on:
  release:
    types:
      - released

name: Jira Release

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Release
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    - name: Setup
      uses: atlassian/gajira-cli@master
      with:
        version: 1.0.20
    - name: Create Jira issue
      run: jira issue AT-1 -a tom.g.r.brooks@gmail.com
    - name: Create Jira version
      run: jira version AT -n ${{ github.event.release.name }}
